version: '2'
services:
  web:
    image: fxt/server
    restart: always
    build: .
    links:
     - db
    container_name: meanjs
    ports:
     - "3000:3000"
     - "80:80"
     - "5858:5858"
     - "8080:8080"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
    volumes_from:
     - web-data
  web-data:
    build: .
    entrypoint: /bin/true
    volumes:
     - ./:/opt/mean.js
     - /opt/mean.js/node_modules
     - /opt/mean.js/public
     - /opt/mean.js/uploads
  db:
    image: mongo:3.4
    restart: always
    ports:
     - "27017"
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.4
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
